version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:      
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
volumes:
  postgres-db: